# Generated by Django 3.0.6 on 2020-06-02 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200601_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incart',
            name='p_id',
        ),
    ]
