# Generated by Django 3.0.6 on 2020-06-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200601_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='incart',
            name='order_status',
            field=models.CharField(max_length=20, null='in_cart'),
            preserve_default='in_cart',
        ),
    ]
