# Generated by Django 3.0.6 on 2020-06-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200602_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incart',
            name='order_status',
        ),
        migrations.AddField(
            model_name='placedorder',
            name='order_status',
            field=models.CharField(max_length=20, null='in_cart'),
            preserve_default='in_cart',
        ),
    ]
