# Generated by Django 3.0.6 on 2020-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200602_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='placed_order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='placed_order_id'),
        ),
    ]
